src/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from .views import register

urlpatterns = [
    url(r'^registrar/', register, name='register'),
    url(r'^entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/', logout, {'next_page': 'accounts:login'}, name='logout'),
]

src/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^mecanica/', include('garages.urls', namespace='garages')),
    url(r'^pesquisa/', include('search.urls', namespace='search')),
    url(r'^veiculo/', include('vehicles.urls', namespace='vehicles')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

src/core/urls.py
from django.conf.urls import url
from .views import home


urlpatterns = [
    url(r'', home, name='home'),
]

src/core/models.py
import re
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _


class Address(models.Model):
    zipcode = models.CharField(
        _('CEP'),
        max_length=9,
        validators=[RegexValidator(regex=re.compile(r'^\d{8}'), message=_('CEP Inválido'))]
    )
    street = models.CharField(_('Logradouro'), max_length=300)
    district = models.CharField(_('Bairro'), max_length=200)
    city = models.CharField(_('Cidade'), max_length=200)
    state = models.CharField(_('Estado'), max_length=2)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.zipcode

    class Meta:
        verbose_name = _('Endereço')
        verbose_name_plural = _('Endereços')


class Tag(models.Model):
    name = models.CharField(_('Nome'), max_length=100, unique=True)
    slug = models.SlugField(_('Slug'), max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

src/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/home.html', {})

src/core/templates/core/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="TheFoody is a food ordering platform which brings restaurants and food lovers together. Food ordering online is easier than any other platforms.">
	<meta name="keywords" content="food, order online, restaurant, reservation, book a table, foodies, cafe, recipes, menu, dishes, chefs and cooking experts ">
	<meta name="author" content="marquesds">

	<title>autoblue - {% block title %}{% endblock title %}</title>
	<!-- reset CSS -->
	<link href="{% static 'autoblue/css/reset.css' %}" rel="stylesheet" type="text/css">
	<!-- Bootstrap css -->
	<link href="{% static 'autoblue/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

	<!-- icon CSS -->
	<link href="{% static 'autoblue/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

	<!-- Main css -->
	<link href="{% static 'autoblue/css/main.css' %}" rel="stylesheet" type="text/css">

	<link rel="shortcut icon" href="{% static 'autoblue/img/autoblue-icon.png' %}" />

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body class="style-2 nav-on-header {% block body_class %}{% endblock body_class %}">

<!-- Start Loading -->
<section class="loading-overlay">
	<div class="Loading-Page">
		<h1 class="loader">Loading...</h1>
	</div>
</section>
<!-- End Loading  -->


<!-- Start Navigation bar -->
<nav class="navbar">
	<div class="container">

		<!-- Logo -->
		<div class="pull-left">
			<a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>
			<div class="logo-wrapper" style="width: 130px; margin-top: 15px;">
				<a class="logo" href="{% url 'core:home' %}"><img src="{% static 'autoblue/img/autoblue-black.png' %}" alt="logo"></a>
				<a class="logo-alt" href="{% url 'core:home' %}"><img src="{% static 'autoblue/img/autoblue-white.png' %}" alt="logo-alt"></a>
			</div>
		</div>
		<!-- END Logo -->

		<!-- User account -->
		<div class="pull-right user-login">
			<a class="btn btn-sm btn-primary" href="{% url 'accounts:login' %}">Login</a> ou &nbsp;
			<a href="{% url 'accounts:register' %}">Registre-se</a>
		</div>
		<!-- END User account -->
	</div>
</nav>
<!-- End Navigation bar -->

{% block content %}
{% endblock content %}

<!-- start footer area -->
<section id="index-footer" class="footer-area-content">

	<!-- Newsletter -->
	<div id="newsletter">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h3><i class="fa fa-envelope-o"></i>Assine nossa newsletter</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="col-sm-8">
						<input type="email" required="required" placeholder="Seu endereço de email" id="email" class="form-control" name="email">
					</div>
					<div class="col-sm-4">
						<a href="#" class="btn btn-subscribe">Assinar</a>
					</div>

				</div>
			</div>
		</div>
	</div>
	<!-- END: Newsletter -->

	<div class="footer-bottom footer-wrapper style-3">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="footer-bottom-navigation">
						<div class="cell-view">
							<div class="footer-links">
								<a href="#">Site Map</a>
								<a href="#">Search</a>
								<a href="#">Terms</a>
								<a href="#">Advanced Search</a>
								<a href="#">Orders and Returns</a>
								<a href="#">Contact Us</a>
							</div>
							<div class="copyright">Created with by <a target="_blank" href="#">autoblue</a> . All right reserved</div>
						</div>
						<div class="cell-view">
							<div class="social-content">
								<a class="post-facebook" href="#"><i class="fa fa-facebook"></i></a>
								<a class="post-google-plus" href="#"><i class="fa fa-google-plus"></i></a>
								<a class="post-twitter" href="#"><i class="fa fa-twitter"></i></a>
								<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- footer area end -->

<!-- Back to top Link -->
<div id="to-top" class="main-bg"><span class="fa fa-chevron-up"></span></div>

<!--Jquery-->
<script src="{% static 'autoblue/js/jquery-1.11.1.min.js' %}"></script>
<!-- Bootstrap Javascript -->
<script src="{% static 'autoblue/js/bootstrap.min.js' %}"></script>

<!-- Mynav Bar Script -->
<script src="{% static 'autoblue/js/app.min.js' %}"></script>

<!-- Custom Javascript -->
<script src="{% static 'autoblue/js/smoothscroll.js' %}"></script>
<script src="{% static 'autoblue/js/wow.min.js' %}"></script>
<script src="{% static 'autoblue/js/custom.js' %}"></script>
</body>
</html>

src/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}home{% endblock title %}

{% block content %}
<!-- Content Start -->

<!-- start static header -->
<section class="static-section">
	<div class="container">
		<div class="row static-header-content-wrapper">
			<div class="col-md-12 static-header-content">
				<div class="static-header-text">
					<h4 class="white">Encontre as melhores oficinas perto de você!</h4>
					<h2 class="white margin-bottom-30">[Alguma coisa legal aqui...]</h2>
				</div>
				<div class="search-form-wrap2">
					<form class="clearfix" action="#">
						<div class="input-field-wrap pull-left">
							<input class="search-form-input" name="key-word" placeholder="DIGITE UM BAIRRO/CIDADE" type="text" />
						</div>
						<div class="select-field-wrap pull-left">
							<select class="search-form-select" name="categories">
								<option class="options" value="all-categories">TIPOS DE SERVIÇO</option>
								<option class="options" value="funilaria">FUNILARIA</option>
								<option class="options" value="injecao_eletronica">INJEÇÃO ELETRÔNICA</option>
								<option class="options" value="revisao">REVISÃO</option>
								<option class="options" value="suspencao">SUSPENÇÃO</option>
							</select>
						</div>
						<div class="submit-field-wrap pull-left">
							<input class="search-form-submit bgblue-1 white" name="key-word" type="submit" value="ENCONTRE UMA OFICINA" />
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- end static header -->

<section id="best-restaurant" class="best-restaurant">
	<div class="container">

		<div class="row">
			<div class="col-md-12 text-center">
				<h2 class="font-lg">Escolha entre as  <span class="font-semibold chef-red">melhores</span>!</h2>
			</div>
			<!-- col-md-12 -->
		</div>

		<!-- Single Garage detail -->
		<div class="row">
			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->

			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->

			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->

			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->

			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->

			<!-- Garage detail -->
			<div class="col-md-6 col-xs-12">
				<div class="item-block">
					<header>
						<a href="#"><img src="{% static 'autoblue/img/cartudo.jpg' %}" alt=""></a>
						<div class="hgroup">
							<h4><a href="#">Cartudo Soluções Automotivas</a></h4>
							<h5>Mecânica Geral<span class="label label-success">Popular</span></h5>
						</div>
						<div class="header-meta">
							<span class="location">São Paulo - SP</span>
						</div>
					</header>

					<footer>
						<p class="status">
                                <span>
												<span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #ED1C3B;"><i class="fa fa-star" ></i></span>
                                <span style="color: #CCCCCC;"><i class="fa fa-star" ></i></span>
                                <span class="review">
													(<span>155</span>)
                                </span>
                                </span>
						</p>
						<div class="action-btn">
							<a class="btn btn-xs btn-primary" href="#">Contratar</a>
						</div>
					</footer>
				</div>
			</div>
			<!-- END Garage detail -->
		</div>
		<!-- End Single Garage detail -->
	</div>
</section>
{% endblock content %}